# Generated by Django 2.1.7 on 2019-02-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='event',
            field=models.ManyToManyField(blank=True, null=True, to='gestor.Event'),
        ),
        migrations.AlterField(
            model_name='member',
            name='event',
            field=models.ManyToManyField(blank=True, null=True, to='gestor.Event'),
        ),
        migrations.AlterField(
            model_name='member',
            name='group',
            field=models.ManyToManyField(blank=True, null=True, to='gestor.Group'),
        ),
        migrations.AlterField(
            model_name='member',
            name='organization',
            field=models.ManyToManyField(blank=True, null=True, to='gestor.Organization'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='event',
            field=models.ManyToManyField(blank=True, null=True, to='gestor.Event'),
        ),
    ]
